apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oposita-data
  namespace: oposita
  labels:
    app.kubernetes.io/name: oposita
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oposita-backups
  namespace: oposita
  labels:
    app.kubernetes.io/name: oposita
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 2Gi
